name: Sync master and main branches

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Sync branches
        run: |
          # Push main to master
          git checkout main
          git push origin main:master --force-with-lease
          
          # Push master to main
          git checkout master
          git push origin master:main --force-with-lease

